package com.avyukt.marketsuite.research.domain;

public enum InsightType {
    COMPETITOR_POSITIONING,
    COMPETITOR_OFFER,
    COMPETITOR_PRICING,
    COMPETITOR_CREATIVE_PATTERN,
    TREND_TOPIC,
    TREND_HASHTAG,
    TREND_AUDIO,
    TREND_FORMAT,
    AUDIENCE_PERSONA,
    AUDIENCE_PAIN_POINT,
    AUDIENCE_OBJECTION,
    AUDIENCE_MOTIVATION,
    KEYWORD_CLUSTER,
    INTENT_CLUSTER,
    CREATIVE_HOOK,
    CREATIVE_ANGLE,
    CREATIVE_CTA_PATTERN,
    CREATIVE_VISUAL_PATTERN
}
