package com.avyukt.marketsuite.integration.domain;

public enum PlatformType {
    META,
    GOOGLE_ADS,
    TIKTOK,
    LINKEDIN,
    X,
    PINTEREST,
    SNAP,
    CHATGPT_ADS,
    PERPLEXITY_ADS,
    GA4,
    GTM,
    SHOPIFY,
    WOOCOMMERCE,
    HUBSPOT,
    SALESFORCE,
    KLAVIYO,
    MAILCHIMP,
    TWILIO,
    WHATSAPP,
    GOOGLE_DRIVE,
    DROPBOX,
    FIGMA,
    CANVA,
    BIGQUERY,
    SNOWFLAKE,
    SEGMENT,
    MPARTICLE,
    CUSTOM,
    OPENAI_API,
    PERPLEXITY_API,
    CUSTOM_LLM
}
