spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  seed-data:
    enabled: true

logging:
  level:
    com.avyukt: DEBUG
    org.springframework.security: DEBUG
